### ISSUE TITLE
Refresh Next.js Quickstart

### ISSUE THREAD

**Issue by rachelnabors** [clerk/clerk-docs#440]
The Clerk Quickstarts are in need of a bit of an update to become our flagship tutorial content type. 

Starting with the [Next.js quickstart](https://clerk.com/docs/quickstarts/nextjs), let's make them easier and clearer to navigate.

Resolving involve:
* Updating the Next.js quickstart
* Updating the two corresponding sample apps for pages and app router
* Adding a styleguide
* And a new template for tutorials

The styleguide and template can be applied to the other quickstart as a follow up.

**Comment by btahir** [comment]
Would appreciate this. Not only are the examples outdated...the documentation is woefully inadequate. I don't know why the decision was made to make all routes private by default. Most apps have 95%+ public routes with a small portion needing to be under auth.

Vercel Builds are failing since 13.6 because of an unzipped 250MB function size (spoiler: your default example of protecting every route is not what we want). I think Clerk also thinks we are regex experts who love trying to come up with matcher + public route + ignored path logic to make things worke that are broken now that were working before.

Besides the performance hit the whole middleware flow is broken for the past 6 months and no one at Clerk seems to care.

**Comment by rachelnabors** [comment]
Hey @btahir! Thanks for reaching out. We updated the [Next.js Quickstart](clerk.com/docs/quickstarts/nextjs) at the end of October to include updated examples. Have you had a chance to look? I've passed along your concerns about the private by default routes. How could this Quickstart help you more?

**Comment by alexisintech** [comment]
Next.js Quickstart was revamped in [this PR ](https://github.com/clerk/clerk-docs/pull/444).
Closing this issue.
